### ISSUE TITLE
Common keybindings for pane/split creation and movement

### ISSUE THREAD

**Issue by radamant** [substantial/atomfiles#10]
For pane creation:

| key | action |
| --- | --- |
| ctrl-shift-s | create horizontal split |
| ctrl-shift-v | create vertical split |

For pane navigation: 

| key | action |
| --- | --- |
| ctrl-shift-h | navigate pane left |
| ctrl-shift-l | navigate pane right |
| ctrl-shift-k | navigate pane up |
| ctrl-shift-j | navigate pane down |
| cmd-h | navigate pane previous (ring movement) |
| cmd-l | navigate pane next |

I know these keys may not be perfect, so please add your $0.02 to the discussion.

**Comment by aaronjensen** [comment]
Another option would be to pick a single leader key for all things pane related. Right now they're using cmd-k, we could use that as well:

| key | action |
| --- | --- |
| cmd-k cmd-s | create horizontal split |
| cmd-k cmd-v | create vertical split |
| cmd-k cmd-h | navigate pane left |
| cmd-k cmd-l | navigate pane right |
| cmd-k cmd-k | navigate pane up |
| cmd-k cmd-j | navigate pane down |
| cmd-k cmd-p | navigate pane previous (ring movement) |
| cmd-k cmd-n | navigate pane next |

The nice thing about grouping things by leader key is they take up less surface area overall. But for something like pane movement, maybe we want something that is really easy to hit....

**Comment by radamant** [comment]
For ring movement you don't want a leader as you often do it multiple times.

**Comment by aaronjensen** [comment]
@radamant let's go w/ what you suggested but cmd-shift instead of ctrl-shift for all
