### ISSUE TITLE
Should we have a table in the readme w/ key bindings?

### ISSUE THREAD

**Issue by aaronjensen** [substantial/atomfiles#15]
I'm trying to open pull requests for new key bindings just so that they are seen, but I'm wondering if we want to have a list in the readme for easy reading or printing

**Comment by gmusick** [comment]
:+1:

**Comment by a-b-r-o-w-n** [comment]
:+1:

**Comment by amay** [comment]
:+1:

**Comment by amay** [comment]
Maybe a good start on this would be to add the table next time we add a package and add the keys for that. Then we will have a place where people can add stuff as necessary.

**Comment by aaronjensen** [comment]
Looks like we have a couple options, either in a wiki or readme.. thoughts on location/formatting/etc?

https://github.com/substantial/atomfiles
https://github.com/substantial/atomfiles/wiki/Keybindings

**Comment by aaronjensen** [comment]
Looks like the readme is staying up to date, so I'm gonna nuke the wiki page
