### ISSUE TITLE
Make it so c-sharp has tab width of 4 spaces

### ISSUE THREAD

**Issue by radamant** [substantial/atomfiles#28]
This is c-sharp standard: "[four character indents, tabs saved as spaces](https://msdn.microsoft.com/en-us/library/ff926074.aspx)" 

Not sure yet how to do this, but there appear to be some ideas here: https://discuss.atom.io/t/different-tab-size-depending-on-language/1523/19 .

**Comment by aaronjensen** [comment]
there's a plugin that does tab detection i thought... that is cool too.

**Comment by aaronjensen** [comment]
https://atom.io/packages/guess-indent try that and see if it helps?

**Comment by aaronjensen** [comment]
oh this one looks more used: https://atom.io/packages/auto-detect-indentation

**Comment by a-b-r-o-w-n** [comment]
Is there a way to configure this on a per language basis?

**Comment by aaronjensen** [comment]
@astephenb the link @radamant put in there has some notes on how to do this which we should do

**Comment by radamant** [comment]
I want this for new files as well, so I'm not sure that any package that looks at file contents to determine tab width will work.

**Comment by aaronjensen** [comment]
@radamant ya, I think the solution in that discuss link will work great. The auto detect is more for OSS contribution where you have to adhere to what they do even if it's wrong.

**Comment by gmusick** [comment]
BTW, the official docs for how to do this are here: https://atom.io/docs/latest/using-atom-basic-customization#language-specific-configuration-settings.

**Comment by radamant** [comment]
@gmusick Fresh. I'm going to make this happen.
