### ISSUE TITLE
Link to Readline key bindings

### ISSUE THREAD

**Issue by amay** [substantial/atomfiles#3]
I think we should link to a good list of Readline key bindings for people who are curious what those are. I tried to google, but it looks like everywhere just states that the default mode for Readline is Emacs and that it can be switched to Vi mode. We could link to Emacs key bindings, but as I understood from your explanation, Readline is just a subset of Emacs. Anyone have a good link?

**Comment by aaronjensen** [comment]
this seems ok: http://www.catonmat.net/download/readline-emacs-editing-mode-cheat-sheet.pdf
