### ISSUE TITLE
Allow ctrl-i to be tab

### ISSUE THREAD

**Issue by radamant** [substantial/atomfiles#34]
Vim users out there may be used to hitting `ctl-[` in place of escape. That's  a control character, and the control character for horizontal tab is [`ctl-i`](https://en.wikipedia.org/wiki/Control_character).

I have grown accustomed to using `ctl-i` rather than tab and would like a way to continue to use it as tab in atom. It has recently been bound as the leader for expand-region, which I have never used. Without that binding, it doesn't appear to do anything in atom. 

I would love it to map to all the things that tab maps to. I could just update the keymap file and open a pull request, but I sense this could be controversial, and I'd rather see the discussion in an issue instead of a PR.

**Comment by aaronjensen** [comment]
could you add some more labels please

expand-region is quite nice and useful (for me) but I don't mind moving its mapping. We could use ctrl-o for inside and ctrl shift o for around?
