### ISSUE TITLE
Add explanation for how to use multiple cursors

### ISSUE THREAD

**Issue by radamant** [substantial/atomfiles#36]
I was going through the readme this morning and this was the one section that left me with a :hurtrealbad: brain.

**Comment by aaronjensen** [comment]
did you try it out? I can see how the bindings wouldn't make much sense w/o actually trying it out and/or being familiar w/ the concept of multiple cursors

**Comment by radamant** [comment]
Yes, I tried it out before filing this issue.

**Comment by aaronjensen** [comment]
cool, what was confusing? asking so i can better know what to write up. If anyone knows of a good explanation of multiple cursors it'd be helpful

**Comment by aaronjensen** [comment]
@radamant I updated the readme, do  you think the notes are clear enough?

**Comment by radamant** [comment]
Much better! I think I would have had an easier time coming to that description fresh. Thanks!

**Comment by aaronjensen** [comment]
![multiple-cursors](https://cloud.githubusercontent.com/assets/8588/8748680/117f7748-2c51-11e5-9366-3280cef0222d.gif)

**Comment by radamant** [comment]
@aaronjensen :heart_eyes_cat:
