### ISSUE TITLE
Should we name the repo simply `atomfiles`?

### ISSUE THREAD

**Issue by aaronjensen** [substantial/atomfiles#8]
At first I wanted to keep substantial in the name to indicate that it was for everyone and so it showed up in forks, but I think it'd show up in forks regardless. I kinda want to just rename it to `atomfiles` now. Thoughts?

**Comment by zachsmith** [comment]
no complaints from me.

**Comment by radamant** [comment]
Like

On Thu, Jul 9, 2015 at 10:12 AM, Zachary Smith notifications@github.com
wrote:

> no complaints from me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/substantial/substantial-atomfiles/issues/8#issuecomment-120074822
> .

## 

Adam Pearson
Substantial Inc.
900 E Pine, Ste 202
Seattle, WA 98122
206.838.0303

**Comment by aaronjensen** [comment]
good enough for me, done.
